[package]
name = "portal-server"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
rusqlite = "0.29.0"
bcrypt = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jsonwebtoken = "8.2"
chrono = "0.4"
